FROM chia-gaming-web
RUN (echo 'from chia_gaming import chia_gaming' ; echo 'chia_gaming.service_main()') > run_simulator.py
CMD /bin/sh -c "(node ./dist/lobby-rollup.cjs --self http://localhost:3001 &) && (sleep 10 ; node ./dist/server-rollup.cjs --self http://localhost:3000 --tracker http://localhost:3001 &) && . /app/test/bin/activate && python3 run_simulator.py"
