packages:
  - "front-end"
  - "hub/hub-frontend"
  - "hub/hub-service"
  - "shared/*"

overrides:
  brace-expansion@5.0.8: 5.0.9
  '@walletconnect/jsonrpc-ws-connection>ws': 8.21.2
  glob: 13.0.6
  test-exclude: 8.0.0

confirmModulesPurge: false

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: false

patchedDependencies:
  "@walletconnect/sign-client@2.23.10": front-end/patches/@walletconnect__sign-client@2.23.10.patch
  "@walletconnect/safe-json@1.0.2": front-end/patches/@walletconnect__safe-json@1.0.2.patch
