confirmModulesPurge: false

patchedDependencies:
  "@walletconnect/sign-client@2.23.9": patches/@walletconnect__sign-client@2.23.9.patch
  "@walletconnect/safe-json@1.0.2": patches/@walletconnect__safe-json@1.0.2.patch
