server {
    listen 0.0.0.0:@PORT@;

    # External URLs (set this to the external url (http or https) of the tracker in use.
    # Host side directory on your web server where you'll put the files to be served.
    set $content_dir /app/lobby-frontend;
    set $content_root $content_dir/public;

    root $content_root;

    location /index.js {
        alias $content_root/index.js;
    }

    location /index.css {
	add_header Content-Type "text/css";
        root $content_dir/dist/css;
    }

    location / {
        root $content_root;
    }

    location ^~ /\&.* {
        root $content_root;
    }

    location /lobby {
        proxy_pass http://localhost:5801;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
    }

    location /game {
        proxy_pass http://localhost:5801;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
    }

    index index.html;
}
