#!/bin/bash -x
#npm install

echo -n "Running game server on port 3001 ..."
node server.js &
echo " started."

echo "Running npm start script ..."
npm start
exit 0

# -------------------------

pid=$(lsof -i -P | grep LISTEN | grep 3001 | awk '{print $2}')

if [ -z "$pid" ]; then
  echo
  echo -n "Running game server on port 3001 ..."
  node server.js &
  echo " started."
else
  echo "Server already running on port 3001, with PID $pid"
  #set -x
  #kill $pid
  #set +x
fi

#echo -n "Running game server on port 3001 ..."
#node server.js &
#echo " started."

npm start


