import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/**/*.{ts,tsx,jsx,js}",
    "./public/index.html"
  ],
  darkMode: "class",

  theme: {
    extend: {
      colors: {
        canvas: {
          DEFAULT: "var(--color-canvas-bg)",
          base: "var(--color-canvas-base)",
          "bg-subtle": "var(--color-canvas-bg-subtle)",
          bg: "var(--color-canvas-bg)",
          "bg-hover": "var(--color-canvas-bg-hover)",
          "bg-active": "var(--color-canvas-bg-active)",
          line: "var(--color-canvas-line)",
          border: "var(--color-canvas-border)",
          "border-hover": "var(--color-canvas-border-hover)",
          solid: "var(--color-canvas-solid)",
          "solid-hover": "var(--color-canvas-solid-hover)",
          text: "var(--color-canvas-text)",
          "text-contrast": "var(--color-canvas-text-contrast)",
          "on-canvas": "var(--color-canvas-on-canvas)",
        },
        primary: {
          DEFAULT: "var(--color-primary-bg)",
          base: "var(--color-primary-base)",
          "bg-subtle": "var(--color-primary-bg-subtle)",
          bg: "var(--color-primary-bg)",
          "bg-hover": "var(--color-primary-bg-hover)",
          "bg-active": "var(--color-primary-bg-active)",
          line: "var(--color-primary-line)",
          border: "var(--color-primary-border)",
          "border-hover": "var(--color-primary-border-hover)",
          solid: "var(--color-primary-solid)",
          "solid-hover": "var(--color-primary-solid-hover)",
          text: "var(--color-primary-text)",
          "text-contrast": "var(--color-primary-text-contrast)",
          "on-primary": "var(--color-primary-on-primary)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary-bg)",
          base: "var(--color-secondary-base)",
          "bg-subtle": "var(--color-secondary-bg-subtle)",
          bg: "var(--color-secondary-bg)",
          "bg-hover": "var(--color-secondary-bg-hover)",
          "bg-active": "var(--color-secondary-bg-active)",
          line: "var(--color-secondary-line)",
          border: "var(--color-secondary-border)",
          "border-hover": "var(--color-secondary-border-hover)",
          solid: "var(--color-secondary-solid)",
          "solid-hover": "var(--color-secondary-solid-hover)",
          text: "var(--color-secondary-text)",
          "text-contrast": "var(--color-secondary-text-contrast)",
          "on-secondary": "var(--color-secondary-on-secondary)",
        },
        success: {
          DEFAULT: "var(--color-success-bg)",
          base: "var(--color-success-base)",
          "bg-subtle": "var(--color-success-bg-subtle)",
          bg: "var(--color-success-bg)",
          "bg-hover": "var(--color-success-bg-hover)",
          "bg-active": "var(--color-success-bg-active)",
          line: "var(--color-success-line)",
          border: "var(--color-success-border)",
          "border-hover": "var(--color-success-border-hover)",
          solid: "var(--color-success-solid)",
          "solid-hover": "var(--color-success-solid-hover)",
          text: "var(--color-success-text)",
          "text-contrast": "var(--color-success-text-contrast)",
          "on-success": "var(--color-success-on-success)",
        },
        warning: {
          DEFAULT: "var(--color-warning-bg)",
          base: "var(--color-warning-base)",
          "bg-subtle": "var(--color-warning-bg-subtle)",
          bg: "var(--color-warning-bg)",
          "bg-hover": "var(--color-warning-bg-hover)",
          "bg-active": "var(--color-warning-bg-active)",
          line: "var(--color-warning-line)",
          border: "var(--color-warning-border)",
          "border-hover": "var(--color-warning-border-hover)",
          solid: "var(--color-warning-solid)",
          "solid-hover": "var(--color-warning-solid-hover)",
          text: "var(--color-warning-text)",
          "text-contrast": "var(--color-warning-text-contrast)",
          "on-warning": "var(--color-warning-on-warning)",
        },
        alert: {
          DEFAULT: "var(--color-alert-bg)",
          base: "var(--color-alert-base)",
          "bg-subtle": "var(--color-alert-bg-subtle)",
          bg: "var(--color-alert-bg)",
          "bg-hover": "var(--color-alert-bg-hover)",
          "bg-active": "var(--color-alert-bg-active)",
          line: "var(--color-alert-line)",
          border: "var(--color-alert-border)",
          "border-hover": "var(--color-alert-border-hover)",
          solid: "var(--color-alert-solid)",
          "solid-hover": "var(--color-alert-solid-hover)",
          text: "var(--color-alert-text)",
          "text-contrast": "var(--color-alert-text-contrast)",
          "on-alert": "var(--color-alert-on-alert)",
        },
        info: {
          DEFAULT: "var(--color-info-bg)",
          base: "var(--color-info-base)",
          "bg-subtle": "var(--color-info-bg-subtle)",
          bg: "var(--color-info-bg)",
          "bg-hover": "var(--color-info-bg-hover)",
          "bg-active": "var(--color-info-bg-active)",
          line: "var(--color-info-line)",
          border: "var(--color-info-border)",
          "border-hover": "var(--color-info-border-hover)",
          solid: "var(--color-info-solid)",
          "solid-hover": "var(--color-info-solid-hover)",
          text: "var(--color-info-text)",
          "text-contrast": "var(--color-info-text-contrast)",
          "on-info": "var(--color-info-on-info)",
        },
      },
    },
  },
} satisfies Config;
