name: Build Ubuntu 20.04 Image

on:
  push:
    branches:
      - main
    paths:
      - 'ubuntu-20.04/*'
      - '.github/workflows/build-ubuntu-20.04.yml'
  pull_request:
    paths:
      - 'ubuntu-20.04/*'
      - '.github/workflows/build-ubuntu-20.04.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'

concurrency:
  # SHA is added to the end of `group` if we are on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      runs-on: ubuntu-22.04
      alternate-latest-mode: true
      dockerfile: "./ubuntu-20.04/Dockerfile"
      dockerhub_imagename: "chianetwork/ubuntu-20.04-builder"
      image_subpath: "ubuntu-20.04-builder"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}